/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSequenceRouteImport } from './routes/_authenticated/sequence'
import { Route as AuthenticatedMailboxRouteImport } from './routes/_authenticated/mailbox'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSequenceRoute = AuthenticatedSequenceRouteImport.update({
  id: '/sequence',
  path: '/sequence',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMailboxRoute = AuthenticatedMailboxRouteImport.update({
  id: '/mailbox',
  path: '/mailbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/mailbox': typeof AuthenticatedMailboxRoute
  '/sequence': typeof AuthenticatedSequenceRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/mailbox': typeof AuthenticatedMailboxRoute
  '/sequence': typeof AuthenticatedSequenceRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/mailbox': typeof AuthenticatedMailboxRoute
  '/_authenticated/sequence': typeof AuthenticatedSequenceRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/mailbox' | '/sequence'
  fileRoutesByTo: FileRoutesByTo
  to: '/login' | '/mailbox' | '/sequence' | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/mailbox'
    | '/_authenticated/sequence'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sequence': {
      id: '/_authenticated/sequence'
      path: '/sequence'
      fullPath: '/sequence'
      preLoaderRoute: typeof AuthenticatedSequenceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mailbox': {
      id: '/_authenticated/mailbox'
      path: '/mailbox'
      fullPath: '/mailbox'
      preLoaderRoute: typeof AuthenticatedMailboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedMailboxRoute: typeof AuthenticatedMailboxRoute
  AuthenticatedSequenceRoute: typeof AuthenticatedSequenceRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedMailboxRoute: AuthenticatedMailboxRoute,
  AuthenticatedSequenceRoute: AuthenticatedSequenceRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
